# =============================================================
# secrets/sqlserver-secret.yaml
# =============================================================
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: inventario
type: Opaque
stringData:
  SQL_PASSWORD: "Itu12345!"
  SECRET_KEY: "egi-inventario-itu-2026-clave-super-secreta-xkcd-9f3a"
