apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: inventario
spec:
  selector:
    app: frontend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort
